### ISSUE TITLE
poor result

### ISSUE THREAD

**Issue by vahidEtt** [daveredrum/Text2Tex#10]
Hello,

I tried to run the pipe on my mesh but the result is quite poor. Do I miss something? It seems the UV mapping could be the problem.

I uploaded the mesh and generated result [here](https://drive.google.com/file/d/1W_ljPB1nZNgSeeNb9FYs2slPDfWFUnPs/view?usp=sharing).

![0_after](https://github.com/daveredrum/Text2Tex/assets/75507961/eab9f964-af91-4200-ba20-9eb86e78a123)
![0_before](https://github.com/daveredrum/Text2Tex/assets/75507961/310f4b1e-d099-4e18-906b-0c9dd515c7d5)
![1_after](https://github.com/daveredrum/Text2Tex/assets/75507961/0f30e8b5-19d1-4ebd-960c-2c45ac34e9d7)
![1_before](https://github.com/daveredrum/Text2Tex/assets/75507961/afacac55-20ab-4257-a566-77f885e4c4a8)

**Comment by JulianKnodt** [comment]
Try reparameterizing your mesh using https://github.com/mworchel/xatlas-python/tree/main, and also try manually triangulating your mesh. It's currently a quad mesh, but the input may expect a tri-mesh.
