### ISSUE TITLE
How can i use a script to transform a mesh without texture into a texture-mesh

### ISSUE THREAD

**Issue by Wei-Qi** [daveredrum/Text2Tex#12]
Thanks for your great work!
How can i use a script to transform a mesh without texture into a texture-mesh? This script must can be calculate uv coordinate.

**Comment by daveredrum** [comment]
Hi @Wei-Qi, I guess you can use `scripts/parameterize_mesh.py` to generate a UV map for the target mesh. Then, you can play around with the texture generation script as the README instructs.

**Comment by Wei-Qi** [comment]
Tanks for your help!!
