### ISSUE TITLE
text driven

### ISSUE THREAD

**Issue by YuzhiChen001** [daveredrum/Text2Tex#2]
Hello, I am very interested in your research.I want to know, if there is no text prompt, can a mesh alone generate texture? Or what happens if the given text doesn't match the mesh? For example, the mesh is a car and the text prompt is a red apple.

**Comment by daveredrum** [comment]
Hi @YuzhiChen001, thanks for your interest in our work! 
1) You can for sure input " " as prompt. Our method will still work in this case. But for sure there's no guarantee what the texture might look like.
2) We've showcased some results where the prompt doesn't match the geometry. Please check them out in the project website or in our paper.
