### ISSUE TITLE
Benchmark against TEXTurePaper

### ISSUE THREAD

**Issue by yosun** [daveredrum/Text2Tex#4]
Hey I am curious how this performs (and which hardware you are using) for a mix of different models, and also against TEXTurePaper

**Comment by reynoldscem** [comment]
It looks like the TEXTure paper is very similar concurrent work. I'd be interested to see a comparison.

**Comment by daveredrum** [comment]
Metric-wise our method is bit higher than TEXTure (FID: 35.68 vs 39.09, KID (x10^-3): 7.74 vs 9.97).
