### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by reynoldscem** [daveredrum/Text2Tex#5]
Now that the paper is accepted to ICCV (congratulations) will the code be released?

**Comment by daveredrum** [comment]
Hi @reynoldscem, we'll release the code in 1-2 weeks.

**Comment by daveredrum** [comment]
Will be a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License as [ScanRefer](https://github.com/daveredrum/ScanRefer/blob/master/LICENSE)

**Comment by reynoldscem** [comment]
@daveredrum Any strong reason for that over MIT?

**Comment by daveredrum** [comment]
Because this is a pure research project, not a codebase for commercial purposes.

**Comment by reynoldscem** [comment]
Makes perfect sense!
