### ISSUE TITLE
No mtl file provided

### ISSUE THREAD

**Issue by LordLiang** [daveredrum/Text2Tex#7]
Thank you for excellent work! I want to generate texture for a simple chair and I have OBJ mesh (I put it into ./data/chair/mesh.obj) but no mtl file.
I run:
```
python scripts/generate_texture.py \
    --input_dir data/chair/ \
    --output_dir outputs/chair \
    --obj_name mesh \
    --obj_file mesh.obj \
    --prompt "wooden chair" \
    --add_view_to_prompt \
    --ddim_steps 50 \
    --new_strength 1 \
    --update_strength 0.3 \
    --view_threshold 0.1 \
    --blend 0 \
    --dist 1 \
    --num_viewpoints 36 \
    --viewpoint_mode predefined \
    --use_principle \
    --update_steps 20 \
    --update_mode heuristic \
    --seed 42 \
    --post_process \
    --device "2080" \
    --use_objaverse
```
then I get this error:
```
=> initializing input arguments...
=> OUTPUT_DIR: outputs/chair/42-p36-h20-1.0-0.3-0.1
=> loading target mesh...
/home/zhoujie/anaconda3/envs/text2tex/lib/python3.9/site-packages/pytorch3d/io/obj_io.py:544: UserWarning: No mtl file provided
  warnings.warn("No mtl file provided")
Traceback (most recent call last):
  File "/home/zhoujie/Projects_08/Text2Tex/scripts/generate_texture.py", line 202, in <module>
    verts_uvs=new_verts_uvs[None, ...]
TypeError: 'NoneType' object is not subscriptable
```
Can you tell me how to prepare the mtl file?

**Comment by daveredrum** [comment]
Hi @LordLiang, I guess you can apply the dummy texture (samples/dummy.png) to your mesh in MeshLab (Filters->Texture->Set Texture), and export the mesh. The .mtl file you were asking for should be available after this.

Or in an even simpler way: copy `data/backpack/mesh.mtl` over to your folder, and add these lines in your .obj file:

```
mtllib mesh.mtl
usemtl mesh
```

Now you should have a material for your untextured mesh.

**Comment by LordLiang** [comment]
> Hi @LordLiang, I guess you can apply the dummy texture (samples/dummy.png) to your mesh in MeshLab (Filters->Texture->Set Texture), and export the mesh. The .mtl file you were asking for should be available after this.
> 
> Or in an even simpler way: copy `data/backpack/mesh.mtl` over to your folder, and add these lines in your .obj file:
> 
> ```
> mtllib mesh.mtl
> usemtl mesh
> ```
> 
> Now you should have a material for your untextured mesh.

Thank you for your reply! I found that if the obj file contains 'vt' info (texture coordination), your suggestion work well. But for a bare mesh which has no 'vt' info (e.g., only contains 'v' and 'f'), UV mapping need to be done first. Finally,  I generated 'vt' info using blender's "smart UV project". ^-^
